# Give SonarQube your specific project identifiers
sonar.projectKey=Avi-Maheshwari121_CI-demo-testing
sonar.organization=avi-maheshwari121

# Tell it where the source code is
sonar.sources=src
sonar.exclusions=src/**/*.test.jsx,src/setupTests.js,src/main.jsx,coverage/**,node_modules/**,dist/**,**/*.html

# Tell it where the tests and coverage reports are
sonar.tests=src
sonar.test.inclusions=src/**/*.test.jsx
sonar.javascript.lcov.reportPaths=coverage/lcov.info